### ISSUE TITLE
On Mobile the date-picker month and year dropdown can't be changed on the modal.

### ISSUE THREAD

**Issue by jonathanenlared** [Strategy11/formidable-modal#11]
### Steps to replicate

1. Create a new form.
2. Add a date field. 
3. Use amodal to embed the form. 
4. Access the form from a mobile device. 

### Test form
https://qa.formidableforms.com/jonathan/wp-admin/admin.php?page=formidable&frm_action=edit&id=984

### Test Modal
https://qa.formidableforms.com/jonathan/modal-test/

Test on Safari on an iPhone with OS version 15.5

**Comment by jonathanenlared** [comment]
Reported here:
https://secure.helpscout.net/conversation/1943628890/103130/

**Comment by Crabcyborg** [comment]
@jonathanenlared This sounds similar to an issue we were seeing in Firefox in the old version of the Bootstrap modal add on (https://github.com/Strategy11/formidable-pro/issues/1179).

Are you still able to replicate this, or does the v3.0 version of the Modal add on fix this for you?

**Comment by jonathanenlared** [comment]
@Crabcyborg  I can confirm the issue is no longer there while using v3.0.2 of the Bootstrap Modal plugin:
https://qa.formidableforms.com/jonathan3/modal-date-field-test/

**Comment by Crabcyborg** [comment]
Thank you @jonathanenlared!

I'll go ahead and close this then.

🚀
