### ISSUE TITLE
The modal won't display when the Jupiter theme is used.

### ISSUE THREAD

**Issue by jonathanenlared** [Strategy11/formidable-modal#12]
1. Create a new form
2. Enable the Boostrap Modal add-on
3. Add the modal to a new page.
4. Enable the JupiterX theme.
5. Click the modal label.

Reported here:https://secure.helpscout.net/conversation/2083909212/123336/

I found a copy of the theme to test.
[jupiterxstablev255.zip](https://github.com/Strategy11/formidable-modal/files/10136119/jupiterxstablev255.zip)

**Comment by Crabcyborg** [comment]
I just tested this. It was an issue in v2.0 but this was fixed with v3.0.

So I'm closing this.

🚀
