### ISSUE TITLE
No button/link shows if nothing is entered in place "Add text" 

### ISSUE THREAD

**Issue by srwells** [Strategy11/formidable-modal#18]
When creating a new Modal, if I don't enter anything for the action text, nothing is shown on my page. I think this will be a source of confusion for people. I would recommend replacing "Add text" with "Click here" and use that text by default so the action always shows. 

The user should still be able to easily change "Click here" to their custom text but it won't result in publishing a page without a way to initiate the modal. 

Hopefully this is a quick fix/improvement.

**Comment by Crabcyborg** [comment]
@truongwp What do you think about this?

Was there any particular reason it was left blank?

**Comment by truongwp** [comment]
@Crabcyborg In the current version, if the trigger text is empty, no link shows. I will do as Steve said above, I'll change the placeholder text to "Click here" and use that text when the trigger text is empty.
