### ISSUE TITLE
Google address autofill does not work when the form is displayed in a modal

### ISSUE THREAD

**Issue by NathanaelJonesIreland** [Strategy11/formidable-modal#21]
Reported here: https://secure.helpscout.net/conversation/2273152302/164675/

Reproduced on my dev site under default conditions.

I've attached two screenshots comparing the modal form vs. the non-modal. The address autofill does not show on the form when it's in a modal. The screenshots are from the users' site - but I saw the same on my dev site with a default WordPress theme and only Formidable plugins active.

![1](https://github.com/Strategy11/formidable-modal/assets/24473311/902eff50-876c-4d3c-afff-b742779f3ad3)
![2](https://github.com/Strategy11/formidable-modal/assets/24473311/271d3ffc-9cfa-414e-893d-bfe06b1417ab)

**Comment by Crabcyborg** [comment]
This is fixed with https://github.com/Strategy11/formidable-modal/pull/28

This was a duplicate issue https://github.com/Strategy11/formidable-geo/issues/51

I'm closing this because it's now completed.

🚀
