### ISSUE TITLE
Bootstrap breaks spacing/alignment with "frm_first frm_two_col frm_half"

### ISSUE THREAD

**Issue by sos12** [Strategy11/formidable-modal#5]
To replicate:

1. Create a checklist field with at least six fields.
2. Use CSS classes: frm_first frm_two_col frm_half
3. Activate Bootstrap modal
![screenshot 2016-06-20 11 28 36](https://cloud.githubusercontent.com/assets/6315034/16204027/3771e9a6-36da-11e6-9f67-3d824f3e5564.png)

**Comment by stephywells** [comment]
Is this a duplicate of this ticket?
https://github.com/Strategy11/formidable-bootstrap/issues/7

**Comment by sos12** [comment]
Closing this, as it does look to be a duplicate of steph's linked issue
