### ISSUE TITLE
When page includes modal, and a modal also exists in page 2 of a multi-page form on that page, second modal link is incorrect

### ISSUE THREAD

**Issue by mswindler** [Strategy11/formidable-modal#8]
Reported here:
https://secure.helpscout.net/conversation/1110272394/24594/

Steps to replicate:
1. Publish a page. On this page, include a modal link to a form.
2. Create a form, add a page break, and an hTML field on page 2
3. Include a modal link in the HTML field
4. Publish the form on the page created in step 1
5. View page, open second modal link in the multi-page form
6. See that the link opens only the first modal (published in the page)

**Comment by Crabcyborg** [comment]
This sounds similar to https://github.com/Strategy11/formidable-modal/issues/10

I can't replicate this either though. The modal links open the expected modals.

**Comment by Crabcyborg** [comment]
@garretlaxton I could use your help trying to verify this bug.

If you can't replicate this either, I think we can close this issue.

Thank you!

**Comment by garretlaxton** [comment]
I couldn't replicate this one.

**Comment by Crabcyborg** [comment]
Thanks Garret!
