### ISSUE TITLE
Bootstrap Modal not working when RTE add media hook is used.

### ISSUE THREAD

**Issue by altoin** [Strategy11/formidable-modal#9]
When this hook https://formidableforms.com/knowledgebase/frm_rte_options/#kb-add-media-button-to-tinymce-editor is used to add a media button to a RichText field, the bootstrap modal doesn't on any page where the Form with the RTE is added.

**Comment by Crabcyborg** [comment]
I just tested this. I can confirm this was a bug in v2.0 but is since fixed in v3.0.1 🚀.
